"""combining id and user_id fields in profile model

Revision ID: 0005
Revises: 0004
Create Date: 2026-03-07 16:38:57.993616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('profiles_user_id_key'), 'profiles', type_='unique')
    op.drop_constraint(op.f('profiles_user_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['id'], ['id'], ondelete='CASCADE')
    op.drop_column('profiles', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_user_id_fkey'), 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('profiles_user_id_key'), 'profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
