"""add root_comment_id and thread_replies_count fields in comment model

Revision ID: 0010
Revises: 0009
Create Date: 2026-05-29 08:47:02.309850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0010'
down_revision: Union[str, Sequence[str], None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_comments', sa.Column('root_comment_id', sa.UUID(), nullable=True))
    op.add_column('post_comments', sa.Column('thread_replies_count', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post_comments', 'post_comments', ['root_comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_comments', type_='foreignkey')
    op.drop_constraint(None, 'post_comments', type_='foreignkey')
    op.drop_column('post_comments', 'thread_replies_count')
    op.drop_column('post_comments', 'root_comment_id')
    # ### end Alembic commands ###
