"""add parent_id and forwarded_from in message model

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-07 19:58:29.386798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0012'
down_revision: Union[str, Sequence[str], None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('forwarded_from', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['forwarded_from'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'messages', 'messages', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'forwarded_from')
    op.drop_column('messages', 'parent_id')
    # ### end Alembic commands ###
