events {}

http {

    upstream frontend {
        server luna_frontend:3000;
    }

    upstream backend {
        server fastapi_app:8000;
    }

    server {
        listen 80;
        server_name luna-sc.ru www.luna-sc.ru;

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name luna-sc.ru www.luna-sc.ru;

        ssl_certificate /etc/nginx/ssl/fullchain.crt;
        ssl_certificate_key /etc/nginx/ssl/private.key;

        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

}